language: python
python: "2.7"
dist: trusty
sudo: required
services:
  - docker

branches:
  only:
    - master
    - dev

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible

  # version checks
  - ansible --version

  # create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - ansible-galaxy install -r requirements.yml
  - ansible-playbook test.yml --syntax-check
  - ansible-playbook test.yml -c local -b

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
